//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sale.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutLang
    {
        public System.Guid AboutLangID { get; set; }
        public Nullable<System.Guid> AboutID { get; set; }
        public string LangID { get; set; }
        public string AboutTitle { get; set; }
        public string AboutContent { get; set; }
        public string AboutContent2 { get; set; }
        public string AboutSubContent { get; set; }
        public string AboutContent3 { get; set; }
        public string AboutName { get; set; }
    }
}
