//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YViet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrugUsingType
    {
        public int DrugUsingTypeID { get; set; }
        public string DrugUsingTypeCode { get; set; }
        public string DrugUsingTypeName { get; set; }
        public string Notes { get; set; }
        public bool IsActive { get; set; }
    }
}
