//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sale.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLang
    {
        public int EmployeeLangID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string LangID { get; set; }
        public string EmployeeName { get; set; }
        public string Position { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
    }
}
