//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sale.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities(string ConnectionString = "DBEntities") : base("name=" + ConnectionString)
        {
            this.Configuration.LazyLoadingEnabled = false;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<About> Abouts { get; set; }
        public virtual DbSet<AboutLang> AboutLangs { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CategoryLang> CategoryLangs { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeLang> EmployeeLangs { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<ImageCategory> ImageCategories { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductLang> ProductLangs { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<ServiceLang> ServiceLangs { get; set; }
        public virtual DbSet<Testimonial> Testimonials { get; set; }
        public virtual DbSet<TestimonialLang> TestimonialLangs { get; set; }
        public virtual DbSet<TextData> TextDatas { get; set; }
        public virtual DbSet<WhyU> WhyUS { get; set; }
        public virtual DbSet<WhyUSDetail> WhyUSDetails { get; set; }
        public virtual DbSet<WhyUSDetailLang> WhyUSDetailLangs { get; set; }
        public virtual DbSet<WhyUSLang> WhyUSLangs { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
    
        public virtual int sp_PostPurchaseInvoice(Nullable<System.Guid> pID, ObjectParameter pError, ObjectParameter pErrorMessage)
        {
            var pIDParameter = pID.HasValue ?
                new ObjectParameter("pID", pID) :
                new ObjectParameter("pID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_PostPurchaseInvoice", pIDParameter, pError, pErrorMessage);
        }
    
        public virtual int sp_UnPostPurchaseInvoice(Nullable<System.Guid> pID, ObjectParameter pError, ObjectParameter pErrorMessage)
        {
            var pIDParameter = pID.HasValue ?
                new ObjectParameter("pID", pID) :
                new ObjectParameter("pID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UnPostPurchaseInvoice", pIDParameter, pError, pErrorMessage);
        }
    
        public virtual int sp_PostPurchaseReturn(Nullable<System.Guid> pID, ObjectParameter pError, ObjectParameter pErrorMessage)
        {
            var pIDParameter = pID.HasValue ?
                new ObjectParameter("pID", pID) :
                new ObjectParameter("pID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_PostPurchaseReturn", pIDParameter, pError, pErrorMessage);
        }
    
        public virtual int sp_UnPostPurchaseReturn(Nullable<System.Guid> pID, ObjectParameter pError, ObjectParameter pErrorMessage)
        {
            var pIDParameter = pID.HasValue ?
                new ObjectParameter("pID", pID) :
                new ObjectParameter("pID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UnPostPurchaseReturn", pIDParameter, pError, pErrorMessage);
        }
    
        public virtual int sp_PostSaleInvoice(Nullable<System.Guid> pID, ObjectParameter pError, ObjectParameter pErrorMessage)
        {
            var pIDParameter = pID.HasValue ?
                new ObjectParameter("pID", pID) :
                new ObjectParameter("pID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_PostSaleInvoice", pIDParameter, pError, pErrorMessage);
        }
    
        public virtual int sp_UnPostSaleInvoice(Nullable<System.Guid> pID, ObjectParameter pError, ObjectParameter pErrorMessage)
        {
            var pIDParameter = pID.HasValue ?
                new ObjectParameter("pID", pID) :
                new ObjectParameter("pID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UnPostSaleInvoice", pIDParameter, pError, pErrorMessage);
        }
    
        public virtual int sp_PostSaleReturn(Nullable<System.Guid> pID, ObjectParameter pError, ObjectParameter pErrorMessage)
        {
            var pIDParameter = pID.HasValue ?
                new ObjectParameter("pID", pID) :
                new ObjectParameter("pID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_PostSaleReturn", pIDParameter, pError, pErrorMessage);
        }
    
        public virtual int sp_UnPostSaleReturn(Nullable<System.Guid> pID, ObjectParameter pError, ObjectParameter pErrorMessage)
        {
            var pIDParameter = pID.HasValue ?
                new ObjectParameter("pID", pID) :
                new ObjectParameter("pID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UnPostSaleReturn", pIDParameter, pError, pErrorMessage);
        }
    
        public virtual int sp_PostCustomerPayment(Nullable<System.Guid> pID, ObjectParameter pError, ObjectParameter pErrorMessage)
        {
            var pIDParameter = pID.HasValue ?
                new ObjectParameter("pID", pID) :
                new ObjectParameter("pID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_PostCustomerPayment", pIDParameter, pError, pErrorMessage);
        }
    
        public virtual int sp_UnPostCustomerPayment(Nullable<System.Guid> pID, ObjectParameter pError, ObjectParameter pErrorMessage, Nullable<bool> pIsThisVoucher)
        {
            var pIDParameter = pID.HasValue ?
                new ObjectParameter("pID", pID) :
                new ObjectParameter("pID", typeof(System.Guid));
    
            var pIsThisVoucherParameter = pIsThisVoucher.HasValue ?
                new ObjectParameter("pIsThisVoucher", pIsThisVoucher) :
                new ObjectParameter("pIsThisVoucher", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UnPostCustomerPayment", pIDParameter, pError, pErrorMessage, pIsThisVoucherParameter);
        }
    }
}
