//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sale.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public System.Guid ProductID { get; set; }
        public string LinkCode { get; set; }
        public string ProductCode { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> DiscountPrice { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> ModifiBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<bool> IsHot { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ImagePath1 { get; set; }
        public string ImagePath2 { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<long> SaleQuanlity { get; set; }
    }
}
