//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YViet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultICD
    {
        public long RowID { get; set; }
        public long ExamResultID { get; set; }
        public int StoreID { get; set; }
        public long ExamID { get; set; }
        public long PatientID { get; set; }
        public string ICD { get; set; }
        public string Notes { get; set; }
        public Nullable<int> SortOrder { get; set; }
    }
}
