//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sale.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestimonialLang
    {
        public System.Guid TestimonialLangID { get; set; }
        public Nullable<int> TestimonialID { get; set; }
        public string LangID { get; set; }
        public string CustomerName { get; set; }
        public string Position { get; set; }
        public string Content { get; set; }
        public string SubContent { get; set; }
    }
}
