//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sale.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public long UserID { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
        public int UserTypeID { get; set; }
        public string Email { get; set; }
        public bool IsFirstChangePassword { get; set; }
        public string Avatar { get; set; }
        public string PageDefault { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Password { get; set; }
    }
}
